apiVersion: apps/v1
kind: Deployment
metadata:
  name: mproc-deployment
  namespace: serverless
  labels:
    app: mproc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mproc
  template:
    metadata:
      labels:
        app: mproc
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker1
      containers:
      - name: flask-mongo
        image: lephuclai/gp_mongo_flask:latest@sha256:14a9296d874e9ed0a4d0de6de62b66214685eb81d42eb2f345c574bede7e1a34
        ports:
        - containerPort: 5500
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mproc-service
  namespace: serverless
spec:
  type: NodePort
  selector:
    app: mproc
  ports:
    - protocol: TCP
      port: 5500
      targetPort: 5500
      nodePort: 30550