apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
  namespace: serverless
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi