apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: serverless
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker1
      containers:
      - name: web
        image: lephuclai/gp_web
        ports:
        - containerPort: 5500
        env:
          - name: MONGODB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-user
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-password
          - name: MONGODB_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: mongo-url
          - name: MONGODB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: mongo-init-db        
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: serverless
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 5500
      targetPort: 5500
      nodePort: 30550 